# Generated by Django 4.1.3 on 2022-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="aadhaarId",
            field=models.CharField(
                help_text="12 digit aadhar no",
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
