# Generated by Django 4.1.3 on 2022-11-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("b", "0003_alter_vitalsign_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsign",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="b.patient"
            ),
        ),
    ]
